name: APK Generator

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Fetch Packages
        run: flutter pub get
      #     - run: flutter test
      - name: Build APK
        run: flutter build apk

      - name: Copy APK To Parent Directory
        run: cp ./build/app/outputs/flutter-apk/app-release.apk ./app.apk

      - name: Commit APK
        run: git add ./app.apk

      - name: Configure Github
        run: |
          git config --local user.email "contact@ishandeveloper.com"
          git config --local user.name "ishandeveloper"
          git commit -m "Generated APK" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
Loading complete
