name: ci
on:
  push:
    branches:
      - master
jobs:
    flutter_test:
      name: Runt flutter tester
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: "11"
        -  uses: subosito/flutter-action@v1
           with:
             channel: "stable"
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test
#    build_ios:
#      name: Build Flutter (iOS)
#      needs: [flutter_test]
#      runs-on: macos-latest
#      steps:
#        - uses: actions/checkout@v2
#        - uses: actions/setup-java@v1
#          with:
#            java-version: "11"
#        - uses: subosito/flutter-action@v1
#          with:
#            channel: "stable"
#        - run: flutter pub get
#        - run: flutter clean
#        - run: flutter build ios

    build_android:
      name: Build Flutter (Android)
      needs: [ flutter_test ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: "11"
        - uses: subosito/flutter-action@v1
          with:
            channel: "stable"
        - name: Download pub dependencies
          run: flutter pub get
        - name: Flutter clean
          run: flutter clean
        - name: Build release .apk
          run: flutter build apk --release
        - name: Build release .aab
          run: flutter build appbundle --release
        - name: Create Github Release
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/*.apk"
            token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}




#build/app/outputs/flutter-apk/app-release.apk
#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