name: ci
on:
  push:
    branches:
      - master
jobs:
    flutter_test:
      name: Runt flutter tester
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: "11"
        -  uses: subosito/flutter-action@v1
           with:
             channel: "stable"
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test


